/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as V2RouteImport } from './routes/v2'
import { Route as TestRouteImport } from './routes/test'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RsvpRouteImport } from './routes/rsvp'
import { Route as MicrographicsRouteImport } from './routes/micrographics'
import { Route as Fall2026RouteImport } from './routes/fall2026'
import { Route as EventsRouteImport } from './routes/events'
import { Route as BlankRouteImport } from './routes/blank'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingIndexRouteImport } from './routes/writing.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WritingSlugRouteImport } from './routes/writing.$slug'
import { Route as URefRouteImport } from './routes/u.$ref'
import { Route as AdminUpdatesRouteImport } from './routes/admin.updates'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminOrganizationsRouteImport } from './routes/admin.organizations'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminAccessRouteImport } from './routes/admin.access'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiCronSyncEventsRouteImport } from './routes/api.cron.sync-events'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiAiChatRouteImport } from './routes/api.ai.chat'
import { Route as AdminUpdatesIdRouteImport } from './routes/admin.updates.$id'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpRoute = RsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => rootRouteImport,
} as any)
const MicrographicsRoute = MicrographicsRouteImport.update({
  id: '/micrographics',
  path: '/micrographics',
  getParentRoute: () => rootRouteImport,
} as any)
const Fall2026Route = Fall2026RouteImport.update({
  id: '/fall2026',
  path: '/fall2026',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const BlankRoute = BlankRouteImport.update({
  id: '/blank',
  path: '/blank',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WritingRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WritingRoute,
} as any)
const URefRoute = URefRouteImport.update({
  id: '/u/$ref',
  path: '/u/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUpdatesRoute = AdminUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncEventsRoute = ApiCronSyncEventsRouteImport.update({
  id: '/api/cron/sync-events',
  path: '/api/cron/sync-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUpdatesIdRoute = AdminUpdatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUpdatesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blank': typeof BlankRoute
  '/events': typeof EventsRoute
  '/fall2026': typeof Fall2026Route
  '/micrographics': typeof MicrographicsRoute
  '/rsvp': typeof RsvpRoute
  '/sign-in': typeof SignInRoute
  '/test': typeof TestRoute
  '/v2': typeof V2Route
  '/writing': typeof WritingRouteWithChildren
  '/admin/access': typeof AdminAccessRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/updates': typeof AdminUpdatesRouteWithChildren
  '/u/$ref': typeof URefRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/writing/': typeof WritingIndexRoute
  '/admin/updates/$id': typeof AdminUpdatesIdRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/sync-events': typeof ApiCronSyncEventsRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/blank': typeof BlankRoute
  '/events': typeof EventsRoute
  '/fall2026': typeof Fall2026Route
  '/micrographics': typeof MicrographicsRoute
  '/rsvp': typeof RsvpRoute
  '/sign-in': typeof SignInRoute
  '/test': typeof TestRoute
  '/v2': typeof V2Route
  '/admin/access': typeof AdminAccessRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/updates': typeof AdminUpdatesRouteWithChildren
  '/u/$ref': typeof URefRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/admin': typeof AdminIndexRoute
  '/writing': typeof WritingIndexRoute
  '/admin/updates/$id': typeof AdminUpdatesIdRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/sync-events': typeof ApiCronSyncEventsRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blank': typeof BlankRoute
  '/events': typeof EventsRoute
  '/fall2026': typeof Fall2026Route
  '/micrographics': typeof MicrographicsRoute
  '/rsvp': typeof RsvpRoute
  '/sign-in': typeof SignInRoute
  '/test': typeof TestRoute
  '/v2': typeof V2Route
  '/writing': typeof WritingRouteWithChildren
  '/admin/access': typeof AdminAccessRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/updates': typeof AdminUpdatesRouteWithChildren
  '/u/$ref': typeof URefRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/writing/': typeof WritingIndexRoute
  '/admin/updates/$id': typeof AdminUpdatesIdRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/sync-events': typeof ApiCronSyncEventsRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/blank'
    | '/events'
    | '/fall2026'
    | '/micrographics'
    | '/rsvp'
    | '/sign-in'
    | '/test'
    | '/v2'
    | '/writing'
    | '/admin/access'
    | '/admin/contacts'
    | '/admin/organizations'
    | '/admin/settings'
    | '/admin/updates'
    | '/u/$ref'
    | '/writing/$slug'
    | '/admin/'
    | '/writing/'
    | '/admin/updates/$id'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/cron/sync-events'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/blank'
    | '/events'
    | '/fall2026'
    | '/micrographics'
    | '/rsvp'
    | '/sign-in'
    | '/test'
    | '/v2'
    | '/admin/access'
    | '/admin/contacts'
    | '/admin/organizations'
    | '/admin/settings'
    | '/admin/updates'
    | '/u/$ref'
    | '/writing/$slug'
    | '/admin'
    | '/writing'
    | '/admin/updates/$id'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/cron/sync-events'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/blank'
    | '/events'
    | '/fall2026'
    | '/micrographics'
    | '/rsvp'
    | '/sign-in'
    | '/test'
    | '/v2'
    | '/writing'
    | '/admin/access'
    | '/admin/contacts'
    | '/admin/organizations'
    | '/admin/settings'
    | '/admin/updates'
    | '/u/$ref'
    | '/writing/$slug'
    | '/admin/'
    | '/writing/'
    | '/admin/updates/$id'
    | '/api/ai/chat'
    | '/api/auth/$'
    | '/api/cron/sync-events'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlankRoute: typeof BlankRoute
  EventsRoute: typeof EventsRoute
  Fall2026Route: typeof Fall2026Route
  MicrographicsRoute: typeof MicrographicsRoute
  RsvpRoute: typeof RsvpRoute
  SignInRoute: typeof SignInRoute
  TestRoute: typeof TestRoute
  V2Route: typeof V2Route
  WritingRoute: typeof WritingRouteWithChildren
  URefRoute: typeof URefRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronSyncEventsRoute: typeof ApiCronSyncEventsRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp': {
      id: '/rsvp'
      path: '/rsvp'
      fullPath: '/rsvp'
      preLoaderRoute: typeof RsvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/micrographics': {
      id: '/micrographics'
      path: '/micrographics'
      fullPath: '/micrographics'
      preLoaderRoute: typeof MicrographicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fall2026': {
      id: '/fall2026'
      path: '/fall2026'
      fullPath: '/fall2026'
      preLoaderRoute: typeof Fall2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blank': {
      id: '/blank'
      path: '/blank'
      fullPath: '/blank'
      preLoaderRoute: typeof BlankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof WritingRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof WritingRoute
    }
    '/u/$ref': {
      id: '/u/$ref'
      path: '/u/$ref'
      fullPath: '/u/$ref'
      preLoaderRoute: typeof URefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/updates': {
      id: '/admin/updates'
      path: '/updates'
      fullPath: '/admin/updates'
      preLoaderRoute: typeof AdminUpdatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync-events': {
      id: '/api/cron/sync-events'
      path: '/api/cron/sync-events'
      fullPath: '/api/cron/sync-events'
      preLoaderRoute: typeof ApiCronSyncEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/updates/$id': {
      id: '/admin/updates/$id'
      path: '/$id'
      fullPath: '/admin/updates/$id'
      preLoaderRoute: typeof AdminUpdatesIdRouteImport
      parentRoute: typeof AdminUpdatesRoute
    }
  }
}

interface AdminUpdatesRouteChildren {
  AdminUpdatesIdRoute: typeof AdminUpdatesIdRoute
}

const AdminUpdatesRouteChildren: AdminUpdatesRouteChildren = {
  AdminUpdatesIdRoute: AdminUpdatesIdRoute,
}

const AdminUpdatesRouteWithChildren = AdminUpdatesRoute._addFileChildren(
  AdminUpdatesRouteChildren,
)

interface AdminRouteChildren {
  AdminAccessRoute: typeof AdminAccessRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUpdatesRoute: typeof AdminUpdatesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessRoute: AdminAccessRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUpdatesRoute: AdminUpdatesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface WritingRouteChildren {
  WritingSlugRoute: typeof WritingSlugRoute
  WritingIndexRoute: typeof WritingIndexRoute
}

const WritingRouteChildren: WritingRouteChildren = {
  WritingSlugRoute: WritingSlugRoute,
  WritingIndexRoute: WritingIndexRoute,
}

const WritingRouteWithChildren =
  WritingRoute._addFileChildren(WritingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlankRoute: BlankRoute,
  EventsRoute: EventsRoute,
  Fall2026Route: Fall2026Route,
  MicrographicsRoute: MicrographicsRoute,
  RsvpRoute: RsvpRoute,
  SignInRoute: SignInRoute,
  TestRoute: TestRoute,
  V2Route: V2Route,
  WritingRoute: WritingRouteWithChildren,
  URefRoute: URefRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronSyncEventsRoute: ApiCronSyncEventsRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
