/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as V2RouteImport } from './routes/v2'
import { Route as TestRouteImport } from './routes/test'
import { Route as RsvpRouteImport } from './routes/rsvp'
import { Route as MicrographicsRouteImport } from './routes/micrographics'
import { Route as Fall2026RouteImport } from './routes/fall2026'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EmailTestRouteImport } from './routes/email-test'
import { Route as BlankRouteImport } from './routes/blank'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingIndexRouteImport } from './routes/writing.index'
import { Route as WritingSlugRouteImport } from './routes/writing.$slug'
import { Route as URefRouteImport } from './routes/u.$ref'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as ApiOpenRefRouteImport } from './routes/api.open.$ref'
import { Route as ApiCronSyncEventsRouteImport } from './routes/api.cron.sync-events'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpRoute = RsvpRouteImport.update({
  id: '/rsvp',
  path: '/rsvp',
  getParentRoute: () => rootRouteImport,
} as any)
const MicrographicsRoute = MicrographicsRouteImport.update({
  id: '/micrographics',
  path: '/micrographics',
  getParentRoute: () => rootRouteImport,
} as any)
const Fall2026Route = Fall2026RouteImport.update({
  id: '/fall2026',
  path: '/fall2026',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailTestRoute = EmailTestRouteImport.update({
  id: '/email-test',
  path: '/email-test',
  getParentRoute: () => rootRouteImport,
} as any)
const BlankRoute = BlankRouteImport.update({
  id: '/blank',
  path: '/blank',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WritingRoute,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WritingRoute,
} as any)
const URefRoute = URefRouteImport.update({
  id: '/u/$ref',
  path: '/u/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/admin/emails',
  path: '/admin/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenRefRoute = ApiOpenRefRouteImport.update({
  id: '/api/open/$ref',
  path: '/api/open/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncEventsRoute = ApiCronSyncEventsRouteImport.update({
  id: '/api/cron/sync-events',
  path: '/api/cron/sync-events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/blank': typeof BlankRoute
  '/email-test': typeof EmailTestRoute
  '/events': typeof EventsRoute
  '/fall2026': typeof Fall2026Route
  '/micrographics': typeof MicrographicsRoute
  '/rsvp': typeof RsvpRoute
  '/test': typeof TestRoute
  '/v2': typeof V2Route
  '/writing': typeof WritingRouteWithChildren
  '/admin/emails': typeof AdminEmailsRoute
  '/u/$ref': typeof URefRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing/': typeof WritingIndexRoute
  '/api/cron/sync-events': typeof ApiCronSyncEventsRoute
  '/api/open/$ref': typeof ApiOpenRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/blank': typeof BlankRoute
  '/email-test': typeof EmailTestRoute
  '/events': typeof EventsRoute
  '/fall2026': typeof Fall2026Route
  '/micrographics': typeof MicrographicsRoute
  '/rsvp': typeof RsvpRoute
  '/test': typeof TestRoute
  '/v2': typeof V2Route
  '/admin/emails': typeof AdminEmailsRoute
  '/u/$ref': typeof URefRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing': typeof WritingIndexRoute
  '/api/cron/sync-events': typeof ApiCronSyncEventsRoute
  '/api/open/$ref': typeof ApiOpenRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/blank': typeof BlankRoute
  '/email-test': typeof EmailTestRoute
  '/events': typeof EventsRoute
  '/fall2026': typeof Fall2026Route
  '/micrographics': typeof MicrographicsRoute
  '/rsvp': typeof RsvpRoute
  '/test': typeof TestRoute
  '/v2': typeof V2Route
  '/writing': typeof WritingRouteWithChildren
  '/admin/emails': typeof AdminEmailsRoute
  '/u/$ref': typeof URefRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/writing/': typeof WritingIndexRoute
  '/api/cron/sync-events': typeof ApiCronSyncEventsRoute
  '/api/open/$ref': typeof ApiOpenRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/blank'
    | '/email-test'
    | '/events'
    | '/fall2026'
    | '/micrographics'
    | '/rsvp'
    | '/test'
    | '/v2'
    | '/writing'
    | '/admin/emails'
    | '/u/$ref'
    | '/writing/$slug'
    | '/writing/'
    | '/api/cron/sync-events'
    | '/api/open/$ref'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/blank'
    | '/email-test'
    | '/events'
    | '/fall2026'
    | '/micrographics'
    | '/rsvp'
    | '/test'
    | '/v2'
    | '/admin/emails'
    | '/u/$ref'
    | '/writing/$slug'
    | '/writing'
    | '/api/cron/sync-events'
    | '/api/open/$ref'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/blank'
    | '/email-test'
    | '/events'
    | '/fall2026'
    | '/micrographics'
    | '/rsvp'
    | '/test'
    | '/v2'
    | '/writing'
    | '/admin/emails'
    | '/u/$ref'
    | '/writing/$slug'
    | '/writing/'
    | '/api/cron/sync-events'
    | '/api/open/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  BlankRoute: typeof BlankRoute
  EmailTestRoute: typeof EmailTestRoute
  EventsRoute: typeof EventsRoute
  Fall2026Route: typeof Fall2026Route
  MicrographicsRoute: typeof MicrographicsRoute
  RsvpRoute: typeof RsvpRoute
  TestRoute: typeof TestRoute
  V2Route: typeof V2Route
  WritingRoute: typeof WritingRouteWithChildren
  AdminEmailsRoute: typeof AdminEmailsRoute
  URefRoute: typeof URefRoute
  ApiCronSyncEventsRoute: typeof ApiCronSyncEventsRoute
  ApiOpenRefRoute: typeof ApiOpenRefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp': {
      id: '/rsvp'
      path: '/rsvp'
      fullPath: '/rsvp'
      preLoaderRoute: typeof RsvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/micrographics': {
      id: '/micrographics'
      path: '/micrographics'
      fullPath: '/micrographics'
      preLoaderRoute: typeof MicrographicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fall2026': {
      id: '/fall2026'
      path: '/fall2026'
      fullPath: '/fall2026'
      preLoaderRoute: typeof Fall2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-test': {
      id: '/email-test'
      path: '/email-test'
      fullPath: '/email-test'
      preLoaderRoute: typeof EmailTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blank': {
      id: '/blank'
      path: '/blank'
      fullPath: '/blank'
      preLoaderRoute: typeof BlankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof WritingRoute
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof WritingRoute
    }
    '/u/$ref': {
      id: '/u/$ref'
      path: '/u/$ref'
      fullPath: '/u/$ref'
      preLoaderRoute: typeof URefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/admin/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/open/$ref': {
      id: '/api/open/$ref'
      path: '/api/open/$ref'
      fullPath: '/api/open/$ref'
      preLoaderRoute: typeof ApiOpenRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync-events': {
      id: '/api/cron/sync-events'
      path: '/api/cron/sync-events'
      fullPath: '/api/cron/sync-events'
      preLoaderRoute: typeof ApiCronSyncEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WritingRouteChildren {
  WritingSlugRoute: typeof WritingSlugRoute
  WritingIndexRoute: typeof WritingIndexRoute
}

const WritingRouteChildren: WritingRouteChildren = {
  WritingSlugRoute: WritingSlugRoute,
  WritingIndexRoute: WritingIndexRoute,
}

const WritingRouteWithChildren =
  WritingRoute._addFileChildren(WritingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  BlankRoute: BlankRoute,
  EmailTestRoute: EmailTestRoute,
  EventsRoute: EventsRoute,
  Fall2026Route: Fall2026Route,
  MicrographicsRoute: MicrographicsRoute,
  RsvpRoute: RsvpRoute,
  TestRoute: TestRoute,
  V2Route: V2Route,
  WritingRoute: WritingRouteWithChildren,
  AdminEmailsRoute: AdminEmailsRoute,
  URefRoute: URefRoute,
  ApiCronSyncEventsRoute: ApiCronSyncEventsRoute,
  ApiOpenRefRoute: ApiOpenRefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
